# Generated by Django 4.2 on 2023-04-17 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_concierto', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_boletos', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artista', to='ConcertBy.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('boletos', models.IntegerField(default=1)),
                ('cancelarTickets', models.BooleanField(default=False)),
                ('concierto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concierto', to='ConcertBy.concierto')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona', to='ConcertBy.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.FloatField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='ConcertBy.ticket')),
            ],
        ),
    ]
