# Generated by Django 4.2 on 2023-05-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConcertBy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concierto',
            name='url_img_concierto',
            field=models.CharField(default='valor predeterminado', max_length=2083),
        ),
    ]
