# Generated by Django 4.2 on 2023-05-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConcertBy', '0002_concierto_url_img_concierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='concierto',
            name='ubicacion',
            field=models.CharField(default='Estadio Modelo', max_length=2083),
        ),
    ]
